In [1]:
import pandas as pd

In [96]:
import numpy as np

In [ ]:
df=pd.read_csv("college-student-placement-factors-dataset/college_student_placement_dataset.csv")

In [113]:
df.head(3)

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,107,6.61,6.28,8,0,8,8,4,0
1,97,5.52,5.37,8,0,7,8,0,0
2,109,5.36,5.83,9,0,3,1,1,0

In [112]:
df['Internship_Experience']=df['Internship_Experience'].replace({"No":0,"Yes":1})

/tmp/ipykernel_55/2125194919.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Internship_Experience']=df['Internship_Experience'].replace({"No":0,"Yes":1})

In [111]:
df.drop("College_ID",inplace=True,axis=1)
df['Internship_Experience']=df['Internship_Experience'].replace({"No":0,"Yes":1})

KeyError: "['College_ID'] not found in axis"

In [100]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Placement'] = le.fit_transform(df['Placement'])

In [114]:
df.head()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,107,6.61,6.28,8,0,8,8,4,0
1,97,5.52,5.37,8,0,7,8,0,0
2,109,5.36,5.83,9,0,3,1,1,0
3,122,5.47,5.75,6,1,1,6,1,0
4,96,7.91,7.69,7,0,8,10,2,0

In [115]:
X.head(2)

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed
0,107,6.61,6.28,8,No,8,8,4
1,97,5.52,5.37,8,No,7,8,0

In [116]:
df.head(2)

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,107,6.61,6.28,8,0,8,8,4,0
1,97,5.52,5.37,8,0,7,8,0,0

In [117]:
X=df.iloc[:,0:8]
y=df.iloc[:,-1]

In [118]:
import seaborn as sns 
from sklearn.preprocessing import LabelEncoder

In [119]:
y.unique()

array([0, 1])

In [120]:
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [121]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [122]:
model = Perceptron(max_iter=1000, eta0=0.1)

In [123]:
model.fit(X_train, y_train)

Perceptron(eta0=0.1)

In [124]:
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.7345